language: objective-c
osx_image: xcode10.2
xcode_project: Form.xcodeproj
xcode_scheme: Form
xcode_sdk: iphonesimulator12.2

script:
  - xcodebuild clean build test -project "Form.xcodeproj" -scheme "Form" -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
